### ISSUE TITLE
Docs: Guidance on using NSpec in dotnet core

### ISSUE THREAD

**Issue by BennieCopeland** [nspec/NSpec#164]
For those wondering how to get started, this is what I figured out so far.

1. Create a new xunittest project by running the command ```dotnet new -t xunittest```
2. Replace ```xunit``` nuget package in the ```project.json``` with ```"NSpec": "2.0.0"```
3. Replace ```dotnet-test-xunit``` nuget package in the ```project.json``` with ```"dotnet-test-nspec": "0.1.0"```
4. Replace ```xunit``` in the ```testRunner``` setting of the ```project.json``` file with ```nspec```
5. Run ```dotnet restore``` followed by ```dotnet test``` to restore and execute the test project.

**Comment by BrainCrumbz** [comment]
Thanks for suggestion, didn't actually think of starting from the xUnit template.

Currently we still lack some documentation on how to setup projects in .NET Core, there's also an issue specific to that (#155 )

**Comment by BennieCopeland** [comment]
I wasn't sure how to create a test project otherwise. I'm now happily converting all my xunit projects over.

**Comment by BrainCrumbz** [comment]
I think we'll be adding those steps you described to the docs as well, @amirrajan

**Comment by amirrajan** [comment]
Let's keep this open till it's added to the website.

**Comment by BrainCrumbz** [comment]
Moving here comments from #155 

***

currently the getting started section is centered around a .NET Framework experience.

Needed settings are different in .NET Core projects. Also, the way to run tests is different as well: there's *dotnet test* (and in the future there will be VS integration, without need for another adapter).

Q1: Where should we put the .NET Core getting started?
Q2: Should we mention that current getting started is for .NET Framework?

***

As a source, we could consider DotNetTestSample [readme](https://github.com/nspec/NSpec/tree/master/sln/test/Samples/DotNetTestSample). As well as examples from other runner, like [dotnet-test-nunit](https://github.com/nunit/dotnet-test-nunit)

***

Suggestion: when mentioning NSpecRunner in *Getting started* chapter, we could mention something like: "to run tests in other scenarios like Visual Studio Test Explorer and .NET Core Command Line Interface, have a look at *Runners* section".  
Then have a Runners section at bottom of page with related info.

***

**Comment by BrainCrumbz** [comment]
Having merged #166 , maybe this issue could be closed? /cc @amirrajan 

Webpage will need to an update anyway when VS IDE integration in .NET Core lands in main branch.
