### ISSUE TITLE
Website: mention solution examples

### ISSUE THREAD

**Issue by BrainCrumbz** [nspec/NSpec#167]
Is it a good idea to mention on the website the available solution examples, as done in [Github readme](https://github.com/nspec/NSpec#samples)?

**Comment by amirrajan** [comment]
Not sure where core is with yeomen templates. But I think that may be better. Isn't there some kind of templating system built into core?

**Comment by BrainCrumbz** [comment]
:) yes there is, it's based off of `dotnet new`. Just starred a technical article speaking about it, but it mentions VC 2017 and the new tooling. Don't know yet if it's available also for VC2015 and current tooling (Preview 2).

http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core

If we get to have that template, of course we would mention it in website. But in the meantime? Just asking.

**Comment by BrainCrumbz** [comment]
There's also something about yeoman, I haven't looked at it though.

**Comment by BrainCrumbz** [comment]
Got a nice answer from [blog post author](http://pioneercode.com/post/how-to-create-a-dot-net-new-project-template-in-dot-net-core#comment-3168402831):

>  I am 99% sure it does not matter if the project is .project.json based or .csproj based. The dotnet new tooling is in the dotnet cli and is not related to the project. You should be able to stick just about anything you want in a template.
