### ISSUE TITLE
Website: describe how to expect exceptions

### ISSUE THREAD

**Issue by BrainCrumbz** [nspec/NSpec#169]
Website makes no mention of how to assert when examples should throw, by using [*expect<>*](https://github.com/nspec/NSpec/blob/fb11cfadc924b0b465c748035c2d62823ffb3ad6/sln/test/NSpec.Tests/WhenRunningSpecs/Exceptions/describe_expected_exception.cs#L19)

**Comment by amirrajan** [comment]
That should be documented, and also this: https://github.com/nspec/NSpec/issues/59

**Comment by BrainCrumbz** [comment]
Closed by b9e0ec3db39b91f7778a6cf52fd70b91bac57abe with both descriptions
