### ISSUE TITLE
DebuggerShim.cs missing using statement for NSpec.Assertions

### ISSUE THREAD

**Issue by BennieCopeland** [nspec/NSpec#172]
Installing the NSpec package into a new .Net 4.6.2 console application, I get an error on line 47 that ```'bool' does not contain a definition for 'ShouldBeTrue' and no extension method 'ShouldBeTrue' accepting a first argument of type 'bool' could be found``` Adding the NSpec.Assertions namespace fixes the issue.

**Comment by amirrajan** [comment]
Thanks for the heads up. Definitely want to make sure the install process is smooth.

**Comment by BrainCrumbz** [comment]
There's an open issue, #161 , tracking a difference in what's reported in website docs and what assertions are actually available.

When you say "on line 47", which code are you referring to? Was that created out of a template, or....? Thanks for your contribution.

**Comment by amirrajan** [comment]
I updated the "hello world" code on the website.

**Comment by BrainCrumbz** [comment]
Just inspected the [sample class](https://github.com/nspec/DotNetNewNSpec/blob/master/Content/CSharp.TestLibrary/describe_sample.cs) generated with `dotnet new nspectest` and that has the right `using NSpec.Assertions;` as well, so it should be ok.

**Comment by BrainCrumbz** [comment]
@amirrajan re. updating example code, just a reminder that with FluentAssertions for basic comparisons one can go with `Should().Be(...)`, which might (?) look more immediate than `ShouldBeEquivalentTo(...)`

**Comment by BennieCopeland** [comment]
Line 47 of the debuggershim.cs file.

**Comment by BrainCrumbz** [comment]
Gosh, that was right in issue title! :O Sorry for not noticing it. Thanks!
