### ISSUE TITLE
NSpec nuget package dependencies issue

### ISSUE THREAD

**Issue by BennieCopeland** [nspec/NSpec#173]
I'm encountering a strange issue using a .Net 4.6.2 console project with NSpec. The `packages\NSpec.3.0.4\lib\net451` folder has several older DLL's besides just NSpec.dll, and these are being added as references in my project. One such example is Newtonsoft.Json.dll. Even though I install the nuget package for Newtonsoft.Json 10.0.1.0, the actual referenced DLL is the 9.0.1.19813 DLL sitting in the NSpec package folder.

**Comment by BennieCopeland** [comment]
I checked the NSpec 2.0 nuget package, and it only contains the NSpec.dll file, not all the other dll's I'm seeing currently.

**Comment by BennieCopeland** [comment]
It happened between version 2.0.1 and 3.0.0. I think it might have something to do with adding Microsoft.Extensions.Testing.Abstractions and Newtonsoft.Json to NSpec's `project.json` file.

**Comment by BrainCrumbz** [comment]
Hi there

Newtonsoft.Json, >= 9.0.1, is an expected dependency in recent NSpec versions: JSON is needed to communicate with new test runners.

What looks strange is that package also contains some NuGet.* DLLs, not sure why: we'll double check on that.

Back to your issue: 

1. to which project do you see DLLs added? If that's the test project, well that's ok.
1. and , to which project you'd like to install Newtonsoft.Json v10? If that's still the test project, maybe you can try adding an app.config to your test project, listing an assemblyBinding like:

```xml
    <assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1">
      <dependentAssembly>
        <assemblyIdentity name="Newtonsoft.Json" publicKeyToken="30ad4fe6b2a6aeed" culture="neutral" />
        <bindingRedirect oldVersion="0.0.0.0-10.0.1.0" newVersion="10.0.1.0" />
      </dependentAssembly>
    </assemblyBinding>
```

and then launch a reinstall from Package Manager Console: 

```shell
PM> Update-Package –reinstall -Project YourTestProject
```

Does that make sense?

**Comment by BrainCrumbz** [comment]
Just fixed the .NET Framework example solution, as it was not propertly upgraded to NSpec 3.0.4. As mentioned, I did a package reinstall to start with a clear state.

Then manual editing of app.config was not really needed: I went to Manage Package for Solution and choose to upgrade Newtonsoft.Json to 10.0.1.0. This is what I got from Output window:

> Attempting to gather dependency information for package 'Newtonsoft.Json.10.0.1' with respect to project 'test\LibrarySpecs', targeting '.NETFramework,Version=v4.5.2'
Gathering dependency information took 2,4 sec
Attempting to resolve dependencies for package 'Newtonsoft.Json.10.0.1' with DependencyBehavior 'Lowest'
One or more unresolved package dependency constraints detected in the existing packages.config file. All dependency constraints must be resolved to add or update packages. If these packages are being updated this message may be ignored, if not the following error(s) may be blocking the current package operation: 'Newtonsoft.Json 9.0.1'
Resolving dependency information took 0 ms
Resolving actions to install package 'Newtonsoft.Json.10.0.1'
Resolved actions to install package 'Newtonsoft.Json.10.0.1'
Retrieving package 'Newtonsoft.Json 10.0.1' from 'nuget.org'.
  GET https://www.nuget.org/api/v2/package/Newtonsoft.Json/10.0.1
Removed package 'Newtonsoft.Json.9.0.1' from 'packages.config'
  OK https://www.nuget.org/api/v2/package/Newtonsoft.Json/10.0.1 429ms
Installing Newtonsoft.Json 10.0.1.
Successfully uninstalled 'Newtonsoft.Json.9.0.1' from LibrarySpecs
Adding package 'Newtonsoft.Json.10.0.1' to folder 'D:\WS\NET\NSpec-framework\NSpec\examples\NetFrameworkSample\packages'
Added package 'Newtonsoft.Json.10.0.1' to folder 'D:\WS\NET\NSpec-framework\NSpec\examples\NetFrameworkSample\packages'
Added package 'Newtonsoft.Json.10.0.1' to 'packages.config'
Executing script file 'D:\WS\NET\NSpec-framework\NSpec\examples\NetFrameworkSample\packages\Newtonsoft.Json.10.0.1\tools\install.ps1'...
Successfully installed 'Newtonsoft.Json 10.0.1' to LibrarySpecs
Removing package 'Newtonsoft.Json.9.0.1' from folder 'D:\WS\NET\NSpec-framework\NSpec\examples\NetFrameworkSample\packages'
Removed package 'Newtonsoft.Json.9.0.1' from folder 'D:\WS\NET\NSpec-framework\NSpec\examples\NetFrameworkSample\packages'
Executing nuget actions took 17,64 sec
========== Finished ==========
Time Elapsed: 00:00:22.3482400

**Comment by BennieCopeland** [comment]
I ended up royally screwing up my project and had to revert back to my last commit, so I am close to where I was when I started having issues. Here is how my projects are, and I came to needing to put this in as a bug:

- .Net Framework 4.6.2 ASP.Net Core project with the following packages
```
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Hosting.WindowsServices" Version="1.1.1" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc" Version="1.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="1.1.1" />
    <PackageReference Include="Microsoft.Extensions.Logging.Debug" Version="1.1.1" />
    <PackageReference Include="MediatR" Version="3.0.1" />
    <PackageReference Include="FluentValidation" Version="6.4.1" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="6.4.0" />
    <PackageReference Include="SimpleInjector" Version="3.3.2" />
    <PackageReference Include="SimpleInjector.Integration.AspNetCore.Mvc" Version="3.3.2" />
    <PackageReference Include="IdentityServer4" Version="1.3.1" />
    <PackageReference Include="StyleCop.Analyzers" Version="1.1.0-beta001">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="AsyncFixer" Version="1.1.5">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Newtonsoft.Json" Version="10.0.1" />
    <PackageReference Include="TopShelf" Version="4.0.3" />
  </ItemGroup>
```
- .Net Framework 4.6.2 Console test project with the following packages
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="FluentAssertions" version="4.19.2" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Hosting" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Hosting.Abstractions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Hosting.Server.Abstractions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Http" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Http.Abstractions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Http.Extensions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.Http.Features" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.TestHost" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.AspNetCore.WebUtilities" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Configuration" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Configuration.EnvironmentVariables" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Configuration.FileExtensions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Configuration.Json" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.DependencyInjection" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.FileProviders.Abstractions" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.FileProviders.Physical" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.FileSystemGlobbing" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.Logging" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.ObjectPool" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.Options" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.Extensions.PlatformAbstractions" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Extensions.Primitives" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Net.Http.Headers" version="1.1.1" targetFramework="net462" />
  <package id="Microsoft.NETCore.Platforms" version="1.1.0" targetFramework="net462" />
  <package id="Microsoft.Win32.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="NETStandard.Library" version="1.6.1" targetFramework="net462" />
  <package id="Newtonsoft.Json" version="10.0.1" targetFramework="net462" />
  <package id="NSpec" version="3.0.3" targetFramework="net462" />
  <package id="Selenium.WebDriver" version="3.3.0" targetFramework="net462" />
  <package id="Selenium.WebDriver.IEDriver" version="3.3.0" targetFramework="net462" />
  <package id="SqlStreamStore" version="0.7.1" targetFramework="net462" />
  <package id="SqlStreamStore.MsSql" version="0.7.1" targetFramework="net462" />
  <package id="System.AppContext" version="4.3.0" targetFramework="net462" />
  <package id="System.Buffers" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections.Concurrent" version="4.3.0" targetFramework="net462" />
  <package id="System.Collections.Immutable" version="1.3.1" targetFramework="net462" />
  <package id="System.ComponentModel" version="4.3.0" targetFramework="net462" />
  <package id="System.Console" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Contracts" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Debug" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Tools" version="4.3.0" targetFramework="net462" />
  <package id="System.Diagnostics.Tracing" version="4.3.0" targetFramework="net462" />
  <package id="System.Globalization" version="4.3.0" targetFramework="net462" />
  <package id="System.Globalization.Calendars" version="4.3.0" targetFramework="net462" />
  <package id="System.IO" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.Compression.ZipFile" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.FileSystem" version="4.3.0" targetFramework="net462" />
  <package id="System.IO.FileSystem.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Linq" version="4.3.0" targetFramework="net462" />
  <package id="System.Linq.Expressions" version="4.3.0" targetFramework="net462" />
  <package id="System.Net.Http" version="4.3.1" targetFramework="net462" />
  <package id="System.Net.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Net.Sockets" version="4.3.0" targetFramework="net462" />
  <package id="System.ObjectModel" version="4.3.0" targetFramework="net462" />
  <package id="System.Reflection" version="4.3.0" targetFramework="net462" />
  <package id="System.Reflection.Extensions" version="4.3.0" targetFramework="net462" />
  <package id="System.Reflection.Metadata" version="1.4.2" targetFramework="net462" />
  <package id="System.Reflection.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Resources.ResourceManager" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Extensions" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Handles" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.InteropServices" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.InteropServices.RuntimeInformation" version="4.3.0" targetFramework="net462" />
  <package id="System.Runtime.Numerics" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Algorithms" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.Primitives" version="4.3.0" targetFramework="net462" />
  <package id="System.Security.Cryptography.X509Certificates" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encoding" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encoding.Extensions" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.Encodings.Web" version="4.3.0" targetFramework="net462" />
  <package id="System.Text.RegularExpressions" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading.Tasks" version="4.3.0" targetFramework="net462" />
  <package id="System.Threading.Timer" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.ReaderWriter" version="4.3.0" targetFramework="net462" />
  <package id="System.Xml.XDocument" version="4.3.0" targetFramework="net462" />
</packages>
```

At the initial stage, the project is still using NSpec 3.0.3, and of the DLLs in the package, this is how the test projects references point:
- Microsoft.DiaSymReader.dll (reference refers to NSpec folder)
- Microsoft.DotNet.InternalAbstractions.dll (reference refers to NSpec folder)
- Microsoft.DotNet.ProjectModel.dll (reference refers to NSpec folder)
- Microsoft.Extensions.DependencyModel.dll (reference refers to NSpec folder)
- Microsoft.Extensions.Testing.Abstractions.dll (reference refers to NSpec folder)
- Newtonsoft.Json.dll (**reference refers to Newtonsoft.Json package**)
- NSpec.dll (reference refers to NSpec folder)
- NuGet.Common.dll (reference refers to NSpec folder)
- NuGet.Frameworks.dll (reference refers to NSpec folder)
- NuGet.Packaging.Core.dll (reference refers to NSpec folder)
- NuGet.Packaging.Core.Types.dll (reference refers to NSpec folder)
- NuGet.RunTimeModel.dll (reference refers to NSpec folder)
- NuGet.Versioning.dll (reference refers to NSpec folder)
- System.Collections.Immutable.dll (**reference refers to System.Collections.Immutable package**)
- System.Reflection.Metadata.dll (**reference refers to System.Reflection.Metadata package**)

After updating to NSpec 3.0.4, the bolded references above, ALL change to use the NSpec folder dll's.

Additionally, when running the test project with a test that uses AspNetCore TestServer, I get the following error:
```
Context Failure: Could not load file or assembly 'Microsoft.Extensions.DependencyModel, Version=1.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040), Example Failure: Object reference not set to an instance of an object.
   at Microsoft.AspNetCore.Mvc.Internal.DefaultAssemblyPartDiscoveryProvider.DiscoverAssemblyParts(String entryPointAssemblyName)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.GetApplicationPartManager(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcCoreServiceCollectionExtensions.AddMvcCore(IServiceCollection services)
   at Microsoft.Extensions.DependencyInjection.MvcServiceCollectionExtensions.AddMvc(IServiceCollection services)
```

So, I figure, ok, I'll just add the package to the test project, but that leads to ANOTHER failure where I'm notified that ```Context Failure: Could not load file or assembly 'SimpleInjector.Extensions.ExecutionContextScoping, Version=3.2.0.0, Culture=neutral, PublicKeyToken=984cb50dea722e99' or one of its dependencies.```

At this point, I start adding all the same packages as the main one. (Looking at it now, it appears that the test project is not getting the DLLs from the sub packages that are not "explicitly" defined in the main project. Packags.config adds every sub dependency reference, but the dotnet core csproj files do not.)

Once all the main packages are added to the test project, THAT is when I start getting the ```Context Failure: Could not load file or assembly 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)```

While I understand that Newtonsoft.Json is now a dependency, in my opinion, it (along with all other dependency DLLs) should not be internal to the NSpec nuget package. Let Nuget handle adding NSpec's dependencies. As of now, I will have to figure out someway to get the references to point to their correct locations, and not NSpecs internal DLLs.

**Comment by BrainCrumbz** [comment]
> While I understand that Newtonsoft.Json is now a dependency, [...]

We'll have a look at what is the *best practice* for this: you might well be right, and hence all non-NSpec DLLs could be removed from package.

**Comment by BrainCrumbz** [comment]
@BennieCopeland try with latest release, [3.0.5](https://github.com/nspec/NSpec/releases/tag/v3.0.5). All those transitive dependencies DLLs have been removed from package, and at least when testing with our examples, they are not re-added as references, nor are found in *bin\* folder.

Newtonsoft.Json remains an explicit dependency, anyway its DLL is **not** packed with NSpec, so when you install NSpec, nuget will also install Newtonsoft.Json and add it as a package reference to you test project. But, differently than before, its hintpath points to its own package directory, not to a DLL beneath NSpec package directory.

HTH

OT shortly there'll be another smaller upgrade, as currently it seems NSpecRunner fails to run from command line.

**Comment by BennieCopeland** [comment]
@BrainCrumbz Looks good. I created a new project, and it pulled in the Newtonsoft.Json dependency as a new packages.config reference.

**Comment by BrainCrumbz** [comment]
Great!

Out of curiosity, what happens to that dotnet issue you opened? Does it still make sense?

**Comment by BennieCopeland** [comment]
Yes. There is still an issue of the test project not getting all the DLL's of the main project. In classic Nuget, when you add a package, it adds explicitly adds its sub dependencies to the packages.config. In .Net Core projects, those sub dependencies are not explicitly added. I think that is causing an issue when referencing a .Net 4.6.2 ASP.Net Core csproj from a standard .Net 4.6.2 Console app. The console app, doesn't see that it needs these 10 other DLL's that are sub dependencies for some top level package.

**Comment by BennieCopeland** [comment]
@BrainCrumbz Is Newtonsoft.Json still required with the new(old) build tools? See: https://github.com/dotnet/cli/issues/4921
