### ISSUE TITLE
NullReferenceException with nested parameterized Tests

### ISSUE THREAD

**Issue by r-weisser** [nspec/NSpec#196]
I'm working with parameterized complex tests (simplified version below).
When using a second parameterized test the 'sub'testvalues are passed through from the top level testcase. Which results in a NullPointer regarding my toplevel `dataManager`.

I already tried to call my testvalue-method directly. This does not work as well. Only instanciating my test object inline seems to work (but not usable because of too much code)

How does building tests influence the object instanciation / execution of before,after steps?
```csharp
void before_all()
{
    dataManager = new DataManager(system);
    dataManager.Setup();
}

void after_all()
{
    dataManager.Cleanup();
}

void one_test()
{
    new Each<string, RecurrentTestParams3>
    {
        { "Description", new RecurrentTestParams3("Param Description", () => dataManager.GetInputDataArray(), () => ValidateData()) }
    }.Do((configName, data) =>
    {
        context["{0} with {1} on {2}".With(configName, data.Name, system)] = () => doCommonTest(configName, data);
    });
}

private void doCommonTest(string configName, RecurrentTestParams3 datas)
{
    it["Basic Check"] = () =>
    {
        sample.ShouldNotBeNull();
    };

    context["Then Process"] = () =>
    {
        new Each<string, MyDataType>
        {
            //{ "One", datas.InputData()[0]}, --original
            //{ "Two", datas.InputData()[1]}, --original
            //{ "Three", datas.InputData()[2]} --original
            //{ "One", dataManager.getData1()}, --modified
            //{ "Two", dataManager.getData2()}, --modified
            //{ "Three", dataManager.getData3()} --modified
            { "One", new MyDataType() }, -- works
            { "Two", new MyDataType()}, -- works
            { "Three", new MyDataType()} -- works
        }.Do((dataName, data) =>
        {
            it["Work {0}".With(dataName)] = () => operationResult = sample.DoWork(data);
        });

        context["Then Validate"] = () =>
        {
            beforeAll = () => results = dataManager.QueryData();

            data.Validator();
        };
    };
}
```

**Comment by BrainCrumbz** [comment]
Hi there. One thing: to ease with trying out, could you provide a dummy `DataManager` impementation, just to keep the test going?

On which line exactly do you get the exception? Could you post the stacktrace?

Also, just to double-check: `before_all`, `after_all` ... and also `beforeAll` in `context["Then Validate"]` will run only once through the whole test run, not once per single test. Is that intended?

Regards

**Comment by amirrajan** [comment]
@r-weisser could you include a stack trace?

**Comment by r-weisser** [comment]
Hi, i just had to make a running sample.
The beforeAll and afterAll block are fine, it's kind of a setup of required data for all tests.

Stack trace looks like:
<pre><code>
Context body throws an exception of type 'NullReferenceException' (1ms) - FAILED - 
While building your test spec, code outside of any test hook threw an exception. 
The whole class or context failed building, and this failing test case took its place. 
Original exception details can be found in 'InnerException' here.Please double check your test code 
and consider running it within 'before' or 'act' hooks.
   at NSpec.nspec.<>c__DisplayClass72_0.<AddFailingExample>b__0()
   at SortedSpecs.Nested_DataInput_Sample.<one_test>b__7_0() in C:\...\Nested_DataInput_Sample.cs:line 30
   at SortedSpecs.Nested_DataInput_Sample.<>c__DisplayClass8_0.<doCommonTest>b__2() in C:\...\Nested_DataInput_Sample.cs:line 48
   at NSpec.nspec.RunContext(Context subContext, Action action)
</code></pre>

Running Sample:

```csharp
using NSpec;
using Shouldly;
using System;

namespace SortedSpecs
{
    class Nested_DataInput_Sample : nspec
    {
        private string system = "systemName";
        private DataManager dataManager;
        private Sample sample;
        private object results;
        private bool operationResult;

        void before_all()
        {
            dataManager = new DataManager(system);
            dataManager.Setup();
        }

        void after_all()
        {
            dataManager.Cleanup();
        }

        void one_test()
        {
            new Each<string, RecurrentTestParams3>
            {
                { "Description", new RecurrentTestParams3("Param Description", () => dataManager.GetInputDataArray(), () => ValidateData()) }
            }.Do((configName, data) =>
            {
                context["{0} with {1} on {2}".With(configName, data.Name, system)] = () => doCommonTest(configName, data);
            });
        }

        private void doCommonTest(string configName, RecurrentTestParams3 insertData)
        {
            beforeAll = () => sample = new Sample();

            it["Basic Check"] = () =>
            {
                sample.ShouldNotBeNull();
            };

            context["Then Process"] = () =>
            {
                new Each<string, string>
                {
                    { "One", insertData.InputData()[0]},  // throws
                    { "Two", insertData.InputData()[1]},
                    { "Three", insertData.InputData()[2]}
                    //{ "One", dataManager.GetInputData1()},  // throws
                    //{ "Two", dataManager.GetInputData2()},
                    //{ "Three", dataManager.GetInputData3()}
                    //{ "One", "a" },  // works
                    //{ "Two", "b"},   
                    //{ "Three", "c"}  
                }.Do((dataName, data) =>
                {
                    it["Work {0}".With(dataName)] = () => operationResult = sample.DoWork(data);
                });

                context["Then Validate"] = () =>
                {
                    before = () => results = dataManager.QueryData();

                    insertData.Validator();
                };
            };
        }

        private void ValidateData()
        {
            it["Result ok"] = () => operationResult.ShouldBeTrue();
            it["Result ok"] = () => results.ShouldNotBeNull();

            it["Content ok"] = () => sample.content.Length.ShouldBe(3);
        }
    }

    public class DataManager
    {
        public DataManager(string system)
        {

        }

        public void Setup() { }
        public void Cleanup() { }

        public string[] GetInputDataArray() { return new[] { "a", "b", "c" }; }

        public string GetInputData1() { return "a"; }
        public string GetInputData2() { return "b"; }
        public string GetInputData3() { return "c"; }
        public object QueryData() { return new object(); }
    }

    public class Sample
    {
        public string content = "";
        public bool DoWork(string something)
        {
            if (!string.IsNullOrWhiteSpace(something))
            {
                content += something;
                return true;
            }

            return false;
        }
    }

    public class RecurrentTestParams3
    {
        public RecurrentTestParams3(string a, Func<string[]> b, Action c)
        {
            Name = a;
            InputData = b;
            Validator = c;
        }

        public string Name { get; private set; }
        public Func<string[]> InputData { get; private set; }
        public Action Validator { get; private set; }
    }
}
```

**Comment by r-weisser** [comment]
Hi,
thanks for your support so far.
I was able to build a running sample which gives me the same error - see below

Looks like it fails while collection all tests before running them. (which also explains beforeAll doesn't run for initialization)
<pre><code>nspec. Nested DataInput Sample. one test. Description with Param Description on systemName. Then Process. 
Context body throws an exception of type 'NullReferenceException'.
While building your test spec, code outside of any test hook threw an exception. The whole class or context failed
building, and this failing test case took its place. Original exception details can be found in 'InnerException' here.
Please double check your test code and consider running it within 'before' or 'act' hooks.
   at NSpec.nspec.<>c__DisplayClass72_0.<AddFailingExample>b__0()
   at SortedSpecs.Nested_DataInput_Sample.<one_test>b__7_0() in C:\...\SortedSpecs\Nested_DataInput_Sample.cs:line 30
   at SortedSpecs.Nested_DataInput_Sample.<>c__DisplayClass8_0.<doCommonTest>b__2() in C:\...\SortedSpecs\Nested_DataInput_Sample.cs:line 48
   at NSpec.nspec.RunContext(Context subContext, Action action)
</code></pre>

Here is the according sample
```cs
using NSpec;
using Shouldly;
using System;

namespace SortedSpecs
{
    class Nested_DataInput_Sample : nspec
    {
        private string system = "systemName";
        private DataManager dataManager;
        private Sample sample;
        private object results;
        private bool operationResult;

        void before_all()
        {
            dataManager = new DataManager(system);
            dataManager.Setup();
        }

        void after_all()
        {
            dataManager.Cleanup();
        }

        void one_test()
        {
            new Each<string, RecurrentTestParams3>
            {
                { "Description", new RecurrentTestParams3("Param Description", () => dataManager.GetInputDataArray(), () => ValidateData()) }
            }.Do((configName, data) =>
            {
                context["{0} with {1} on {2}".With(configName, data.Name, system)] = () => doCommonTest(configName, data);
            });
        }

        private void doCommonTest(string configName, RecurrentTestParams3 insertData)
        {
            beforeAll = () => sample = new Sample();

            it["Basic Check"] = () =>
            {
                sample.ShouldNotBeNull();
            };

            context["Then Process"] = () =>
            {
                new Each<string, string>
                {
                    { "One", insertData.InputData()[0]},  // throws
                    { "Two", insertData.InputData()[1]},
                    { "Three", insertData.InputData()[2]}
                    //{ "One", dataManager.GetInputData1()},  // throws
                    //{ "Two", dataManager.GetInputData2()},
                    //{ "Three", dataManager.GetInputData3()}
                    //{ "One", "a" },  // works
                    //{ "Two", "b"},
                    //{ "Three", "c"}
                }.Do((dataName, data) =>
                {
                    it["Work {0}".With(dataName)] = () => operationResult = sample.DoWork(data);
                });

                context["Then Validate"] = () =>
                {
                    before = () => results = dataManager.QueryData();

                    insertData.Validator();
                };
            };
        }

        private void ValidateData()
        {
            it["Result ok"] = () => operationResult.ShouldBeTrue();
            it["Result ok"] = () => results.ShouldNotBeNull();

            it["Content ok"] = () => sample.content.Length.ShouldBe(3);
        }
    }

    public class DataManager
    {
        public DataManager(string system)
        {

        }

        public void Setup() { }
        public void Cleanup() { }

        public string[] GetInputDataArray() { return new[] { "a", "b", "c" }; }

        public string GetInputData1() { return "a"; }
        public string GetInputData2() { return "b"; }
        public string GetInputData3() { return "c"; }
        public object QueryData() { return new object(); }
    }

    public class Sample
    {
        public string content = "";
        public bool DoWork(string something)
        {
            if (!string.IsNullOrWhiteSpace(something))
            {
                content += something;
                return true;
            }

            return false;
        }
    }

    public class RecurrentTestParams3
    {
        public RecurrentTestParams3(string a, Func<string[]> b, Action c)
        {
            Name = a;
            InputData = b;
            Validator = c;
        }

        public string Name { get; private set; }
        public Func<string[]> InputData { get; private set; }
        public Action Validator { get; private set; }
    }
}
```

**Comment by BrainCrumbz** [comment]
Yes. The framework incurred in an exception not while actually running the tests, but in an earlier step, when it runs through your nspec-derived classes, in order to build the hierarchy of `context`s, `before`s, `it`s, `after`s and so on.

Taking for now just this bit of stacktrace:

>   at SortedSpecs.Nested_DataInput_Sample.b__7_0() in C:\...\SortedSpecs\Nested_DataInput_Sample.cs:line 30
   at SortedSpecs.Nested_DataInput_Sample.<>c__DisplayClass8_0.b__2() in C:\...\SortedSpecs\Nested_DataInput_Sample.cs:line 48

what are those line 30 and 48 doing? If you posted the file in its entirety, they should be:

```cs
{ "Description", new RecurrentTestParams3("Param Description", () => dataManager.GetInputDataArray(), () => ValidateData()) }  // # line 30

// ...

new Each<string, string>  // # line 48
```

Now, at line 30 you're trying to use `dataManager`, in a piece of code that it is actually **building** your tests, not **running** them. At that time, `before_all` has not run yet (nor any other hook, for that matters). So you're invoking methods on `dataManager` instance which has not been created yet.

The more code you put outside of straightforward `before`, `after`, `it[]` blocks, the more chances are that you can incur in this situation and not get any test output at all, which makes things harder to debug. That's why it is advisable to reduce code outside of test hooks, and keep code and data as confined as possible within contexts and test blocks.

HTH

**Comment by BrainCrumbz** [comment]
Ideally, try to distinguish as much as possible the code/classes/objects you need to build tests from the code/classes/objects that you actually use and exercise while running tests. As said, try also to keep the former to a minimum.

**Comment by r-weisser** [comment]
Yes, I guess I'm just digging into it and this seems to be the best approach.
I wasn't aware of this way of functionality and that I mixed testdata with data needed to build test context.

Regards

**Comment by BrainCrumbz** [comment]
The way we create parametric tests in my team is:

1. create a kind of blueprint/template of actual test code, with all `context`s and `before`s, `it`s, etc. in place, where the only *holes* are actual data, say for example `string scenario, int limit, double expected`. 

    ```cs
    context[$"given {scenario}"] = () =>
    {
      before = () =>
      {
        // ...
        someMock.Limit = limit;
        // ...
      };
      
      it[$"returns {expected}"] = () =>
      {
        // ...
        actual.Should().Be(expected);
      };
    }
    ```

1. Then we define locally some `TestDataPoint` class that's just a tuple holding the needed data values:

    ```cs
    class TestDataPoint
    {
      string scenario;
      int limit;
      double expected;

      // maybe, a costructor to set values
    }
    ```

1. move the test code blueprint into some `buildContext(TestDataPoint point)` method. And iterate over some data set in order to generate tests. 

    ```cs
    new []
    {
      new TestDataPoint(/* ... */),
      new TestDataPoint(/* ... */),
      new TestDataPoint(/* ... */),

    }.Do(buildContext);
    ```

(please forgive any syntax error, that was just typed in here)

Less moving parts between test-build and test-run time, just data generated and passed along. HTHT
