### ISSUE TITLE
Running Multiple Assembly With Nspec

### ISSUE THREAD

**Issue by satish860** [nspec/NSpec#57]
We have a both Acceptance test and Unit test with the Nspec . I would like to run all the dll at once and get the report out of it . Currently it takes only one Assembly . I have forked the code to look at a way to do it

**Comment by amirrajan** [comment]
Still relevant, but issue will be resolved once NSpec requires all devs to create their own Program.cs/Console app (which will be stupid simple)

**Comment by BrainCrumbz** [comment]
Should we close this? Not sure how to move on or what to do. Provide instructions/ samples/ docs?

**Comment by amirrajan** [comment]
Yep. Close it. The answer is: build your own console app.
