### ISSUE TITLE
Data-driven tests & dynamically-generated tests

### ISSUE THREAD

**Issue by petemounce** [nspec/NSpec#64]
Xunit has awesome support for data-driven tests via the Theory attribute.

However, MbUnit goes one better and allows one to [generate test cases in loops](http://bugsquash.blogspot.com/2012/05/first-class-tests-in-mbunit.html) - [RSpec also allows this](http://testobsessed.com/2009/09/adventures-with-auto-generated-tests-and-rspec/) (and IMO a bit more slickly, but that's probably ruby rather than the framework), and it's really powerful to just write standard code to generate test cases instead of learn test framework features to do so.

Can NSpec do this already, and if not, please could it join in?

**Comment by dhilgarth** [comment]
The problem I have with that approach is the following:
While the test code is rather clean, i.e. it is obvious that for all different data the specs are the same, the same cannot be said for the generated specs output. I.e. the actual domain expert that verifies the logic that is defined in the tests, needs to reason for each loop iteration. In my case, I have a rather complex test with different contexts and specs that should all be true for different inputs. So I created a loop around it. But now the generated spec result explodes.
How is this usually solved?
